// Panel router. Imports panels via /panels/index.js (auto-generated by the
// server at startup) and renders the one matching window.location.hash.

import panels from "/panels/index.js";

const byId = Object.fromEntries(panels.map(p => [p.id, p]));

function makeApi(panelId) {
  const base = `/api/${panelId}`;
  async function jsonOrThrow(resp) {
    const data = await resp.json().catch(() => ({}));
    if (!resp.ok) throw new Error(data.error || resp.statusText);
    return data;
  }
  return {
    get: (sub) => fetch(`${base}/${sub}`).then(jsonOrThrow),
    post: (sub, body) => fetch(`${base}/${sub}`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body || {}),
    }).then(jsonOrThrow),
    notify,
    confirm: (msg) => Promise.resolve(window.confirm(msg)),
  };
}

function notify(msg, kind = "info") {
  const div = document.createElement("div");
  div.className = `toast ${kind}`;
  div.textContent = msg;
  document.getElementById("toasts").appendChild(div);
  setTimeout(() => div.remove(), 3500);
}

const nav = document.getElementById("nav");
const content = document.getElementById("content");

const sorted = panels.slice().sort(
  (a, b) => (a.order ?? 99) - (b.order ?? 99)
);

for (const p of sorted) {
  const btn = document.createElement("button");
  btn.className = "nav-link";
  btn.dataset.id = p.id;
  btn.innerHTML = `<span>${p.icon || ""}</span><span>${p.title}</span>`;
  btn.onclick = () => { window.location.hash = p.id; };
  nav.appendChild(btn);
}

let currentId = null;
async function route() {
  const id = (window.location.hash || "").replace("#", "")
    || sorted[0]?.id || null;
  if (!id || !byId[id]) {
    content.innerHTML = "<p>No panel selected.</p>";
    return;
  }
  if (currentId && byId[currentId]?.unmount) {
    byId[currentId].unmount(content);
  }
  content.innerHTML = "";
  for (const btn of nav.querySelectorAll(".nav-link")) {
    btn.classList.toggle("active", btn.dataset.id === id);
  }
  try {
    await byId[id].mount(content, makeApi(id));
  } catch (e) {
    console.error(e);
    notify("panel failed to load: " + e.message, "error");
  }
  currentId = id;
}

window.addEventListener("hashchange", route);
route();
